# Generated by Django 3.1.3 on 2020-12-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicPlace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='rate',
            field=models.FloatField(blank=True),
        ),
    ]
