# Generated by Django 3.1.3 on 2020-12-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicPlace', '0002_auto_20201221_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='num_of_rates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medic',
            name='sum_of_rates',
            field=models.IntegerField(default=0),
        ),
    ]
