# Generated by Django 3.1.3 on 2020-12-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicPlace', '0004_article_comment_medic_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_comment',
            name='comment',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='medic_article',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
