# Generated by Django 3.1.3 on 2020-12-26 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicPlace', '0005_auto_20201223_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_of_medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Active_ingredient', models.CharField(max_length=30)),
                ('Summary', models.TextField(max_length=1000)),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicPlace.medic')),
                ('type_of_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicPlace.type_of_medicine')),
            ],
        ),
    ]
